# This file was generated by GoReleaser. DO NOT EDIT.
cask "yuno-cli" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "1c43d208de9cd5cd43a8a48c5e4052e8d02a5f52e3b3ce21bcc9b86d1f03d98f"
      url "https://github.com/pvarganov/yuno-cli/releases/download/v#{version}/yuno-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "253b3b8c75d54ed9fac150f6030fe3c44c536e7486686c776cd0e8e259fd47b5"
      url "https://github.com/pvarganov/yuno-cli/releases/download/v#{version}/yuno-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "caeae5aa3d101be70d1508fae031e0c60ed0bd7220c9c392ae6b2eaa41b658cf"
      url "https://github.com/pvarganov/yuno-cli/releases/download/v#{version}/yuno-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d637b285a20224f945cc8ff5255ba5d2c4908a759f8e189e976e9f937045d979"
      url "https://github.com/pvarganov/yuno-cli/releases/download/v#{version}/yuno-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "yuno-cli"
  desc "CLI for the full Yuno REST API"
  homepage "https://github.com/pvarganov/yuno-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yuno-cli"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yuno-cli"]
    end
  end

  # No zap stanza required
end
