# This file was generated by GoReleaser. DO NOT EDIT.
cask "yuno-cli" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "7dbf94934365389af4fddb11c4b2692b9ca0c58efa53ff8c90c25f0fd4aaa765"
      url "https://github.com/pvarganov/yuno-cli/releases/download/v#{version}/yuno-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4c9f4333186f7224fd9816a12fdc0331a73fdf235628ca2f2eb27b187ca9dc08"
      url "https://github.com/pvarganov/yuno-cli/releases/download/v#{version}/yuno-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ce2d0c450116ad08ee8f86d3325035d88811e3ebd6fdaf67591ba1178bfb8b6a"
      url "https://github.com/pvarganov/yuno-cli/releases/download/v#{version}/yuno-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ba8f6042082bbc5803f95d077d80f0be14bd6e460e4eb590f76256d4fe5cdf41"
      url "https://github.com/pvarganov/yuno-cli/releases/download/v#{version}/yuno-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "yuno-cli"
  desc "CLI for the full Yuno REST API"
  homepage "https://github.com/pvarganov/yuno-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yuno-cli"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yuno-cli"]
    end
  end

  # No zap stanza required
end
