# This file was generated by GoReleaser. DO NOT EDIT.
cask "yuno-cli" do
  version "0.1.4"

  on_macos do
    on_arm do
      sha256 "756600fceb1a4aea7e7f304ce3e50754032d1423b0aa05ba33928014b1742622"
      url "https://github.com/pvarganov/yuno-cli/releases/download/v#{version}/yuno-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3768df200dca73d8f7f8cc19c68f1369901a97f41a2a778ef7d359572bb1ff90"
      url "https://github.com/pvarganov/yuno-cli/releases/download/v#{version}/yuno-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7e7a9ba7209c3a7b7e1a02093ea2b5b552359de9ebbf3d87e9bd84549c2738f9"
      url "https://github.com/pvarganov/yuno-cli/releases/download/v#{version}/yuno-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9e1373eb80922dad960f5d697c976f5cad0c7b13671731b14f2ac30271fa5607"
      url "https://github.com/pvarganov/yuno-cli/releases/download/v#{version}/yuno-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "yuno-cli"
  desc "CLI for the full Yuno REST API"
  homepage "https://github.com/pvarganov/yuno-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yuno-cli"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yuno-cli"]
    end
  end

  # No zap stanza required
end
